### ISSUE TITLE
Question about 02 TCIA Pancreas Dataset

### ISSUE THREAD

**Issue by Tianananana** [ljwztc/CLIP-Driven-Universal-Model#35]
Hi, I am trying to replicate your code, and am downloading the datasets. However, when I tried to arrange the datasets following 
` dataset/dataset_list/PAOT.txt`, the format for 02 [Pancreas-CT TCIA](https://wiki.cancerimagingarchive.net/display/Public/Pancreas-CT) are dicom images of each slice. Can I check if you have any preprocessing code to convert the dicom format into `.nii.gz`? Thank you!

**Comment by ljwztc** [comment]
Sorry, I cannot find my preprocess code since it has been too long. But you can have a try with (dicom2nifti.convert_dicom.dicom_series_to_nifti)[https://dicom2nifti.readthedocs.io/en/latest/dicom2nifti.convert_dicom.html] or you can take a look for (this page)[https://github.com/JunMa11/PrePostSeg/blob/623fa56f76a8a5d1af388c6a53a8e689cc53cde1/dcm2nii/NIHPancreasCT.py#L5]
