### ISSUE TITLE
Pre trained weights on MSD challenge

### ISSUE THREAD

**Issue by ghost** [ljwztc/CLIP-Driven-Universal-Model#66]
Could we get the pre-trained weights that are used for the MSD challenge where the model in_channels = 4?
Thanks

**Comment by ljwztc** [comment]
We do not train the model with `in_channels=4`. The specialized model trained for the MSD submission has been deleted due to limited storage. Instead, we have released the model weights that perform well for generalization. For your information, we have updated the tutorial to inference without ground truth.
